### ISSUE TITLE
Undersøg brugen af proxy (kan det lade sig gøre)

### ISSUE THREAD

**Issue by csbc92** [Vedsted/MobileSystemsProject#2]

**Comment by Vedsted** [comment]
[sandrop](https://code.google.com/archive/p/sandrop/wikis/HowToInterceptTrafficOnMyOwn.wiki)

**Comment by csbc92** [comment]
Det lader ikke til at Proxy er det mest optimale valg. App udviklere gør primært brug af VPN, DNS og hosts files.
